### ISSUE TITLE
Unable to control fan speed on GPD WIN 4

### ISSUE THREAD

**Issue by ok100** [mengmeet/PowerControl#10]
Although the current fan speed is being displayed correctly, attempting to create and apply a fan profile does not appear to result in any change to the fan speed.

OS: ChimeraOS 41, BIOS: 3.03

**Comment by Gawah** [comment]
This problem is known for now.It seems to be caused by the ec of the fan speed not writing properly.The EC reading and writing method used in Win4 is different from other handheld.I don't have this device so I'll need some time to collaborate with others who have this device to test and fix it.

**Comment by danyi** [comment]
This problem has been fixed

**Comment by ok100** [comment]
The fan control has been fixed on the main branch, but it seems like this change has introduced a new issue. Sometimes, after using the device unplugged for a while, the battery indicator disappears from MangoHud overlay. A simple reboot doesn't fix it; I have to reset the device by holding down the power button. The battery indicator is also missing when rebooting to Windows when this happens.

**Comment by danyi** [comment]
I've tested it many times and it doesn't show up like this
You need to consider whether the battery is dead first
Or the battery is protected

**Comment by Gawah** [comment]
> The fan control has been fixed on the main branch, but it seems like this change has introduced a new issue. Sometimes, after using the device unplugged for a while, the battery indicator disappears from MangoHud overlay. A simple reboot doesn't fix it; I have to reset the device by holding down the power button. The battery indicator is also missing when rebooting to Windows when this happens.

I apologize for the late reply, as I have been quite busy recently. According to the feedback from my testing partner, the plugin is working well on his Win4. He mentioned that a similar issue had occurred before, but it was resolved after returning and changing the battery. Therefore, I want to make sure this is not a hardware issue first. Are you certain that this issue did not occur before the fan control was fixed? If so, you can try uninstalling the plugin and see if the issue still persists. If it is confirmed to be caused by my plugin, I will do my best to find the problem and fix it within my abilities.

**Comment by ok100** [comment]
I haven't encountered this issue with a version of this plugin without fan control (https://github.com/oliverchang/PowerControl), or without the plugin.

**Comment by ok100** [comment]
Controlling the fan speed with `EC.RamRead` and `EC.RamWrite` seems to fix the battery issue on my device.
